
name: CEDAR Template GitHub Pipeline

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      google_sheet_name:
        description: 'Google Sheet Name for the CEDAR Template'
        required: true
      google_sheet_id:
        description: 'Google Sheet ID for the CEDAR Template'
        required: false
        default: '1Kwe4PFodciXo-XDX2bHN8F-CRAmopguoI9YKFX6piaQ'
      template_folder_id:
        description: 'Template ID in CEDAR'
        required: true

jobs:
  cedar_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download Google Sheet as CSV
        run: |
          sheet_name="${{ github.event.inputs.google_sheet_name }}"
          sheet_id="${{ github.event.inputs.google_sheet_id }}"
          encoded_sheet_name=$(echo "${sheet_name}" | sed 's/ /%20/g')
          csv_url="https://docs.google.com/spreadsheets/d/${sheet_id}/gviz/tq?tqx=out:csv&sheet=${encoded_sheet_name}"
          echo "Downloading CSV from: $csv_url"
          curl -o template.csv "$csv_url"
          echo "Downloaded CSV file content:"
          cat template.csv

      - name: Commit CSV to Repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add template.csv
          git commit -m "Add updated template CSV file"
          git push


      - name: Update README.md
        run: |
          sheet_url="https://docs.google.com/spreadsheets/d/${{ github.event.inputs.google_sheet_id }}/edit#gid=${{ github.event.inputs.google_sheet_name }}"
          repo_url="https://github.com/${{ github.repository }}"
          template_url = "${repo_url}/blob/${{ github.ref }}/RADxMetadataSpecification.json"
          template_folder_url="https://cedar.metadatacenter.org/dashboard?folderId=${{ github.event.inputs.template_folder_id }}"
          docs_url="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/docs.md"
          echo "Updating README.md with the following information:"
          echo "Google Sheet URL: $sheet_url"
          echo "CEDAR Template in Repo: $template_url"
          echo "CEDAR Template in CEDAR: https://cedar.metadatacenter.org/dashboard?folderId='${{ github.event.inputs.template_folder_id }}'"
          echo "Documentation URL: $docs_url"
          sed -i 's|<GOOGLE_SHEET_URL>|'"$sheet_url"'|g' README.md
          sed -i 's|<CEDAR_TEMPLATE_REPO_URL>|'"$template_url"'|g' README.md
          sed -i 's|<CEDAR_TEMPLATE_CEDAR_URL>|'"$template_folder_url"'|g' README.md
          sed -i 's|<DOCUMENTATION_URL>|'"$docs_url"'|g' README.md
          git add README.md
          git commit -m "Update README.md with new template and documentation links"
          git push origin main

#      - name: Create GitHub Release
#        uses: actions/create-release@v1
#        env:
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#        with:
#          tag_name: "v1.0.0" # Update this as needed
#          release_name: "CEDAR Template Release v1.0.0"
#          body: |
#            - Google Sheet: [${{ steps.extract.outputs.sheet_name }}]($sheet_url)
#            - CEDAR Template in Repo: [template.json](template.json)
#            - CEDAR Template in CEDAR: [CEDAR Template]($cedar_template_url)
#            - Documentation: [documentation.md]($docs_url)
#          draft: false
#          prerelease: false

#      - name: Make Read-Only Copy of Google Sheet
#        run: |
#          echo "Making a read-only copy of the Google Sheet"
#          # Additional steps to copy the Google Sheet and make it read-only could be added here if possible
