name: Copy and Protect Google Sheet

on:
  workflow_dispatch:
    inputs:
      google_spreadsheet_id:
        description: 'Google Spreadsheet ID'
        default: '1Kwe4PFodciXo-XDX2bHN8F-CRAmopguoI9YKFX6piaQ'
        required: false
      google_sheet_id:
        description: 'Google Sheet ID'
        default: '118145754'
        required: false
      new_sheet_name:
        description: 'New Sheet name'
        default: 'V0.0.1'
        required: false

jobs:
  copy_and_protect_sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install googleapis

      - name: Authenticate with Google
        id: auth
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json

      - name: Copy and Protect Sheet
        env:
          GOOGLE_SPREADSHEET_ID: ${{ github.event.inputs.google_spreadsheet_id }}
          GOOGLE_SHEET_ID: ${{ github.event.inputs.google_sheet_id }}
          NEW_SHEET_NAME: ${{ github.event.inputs.new_sheet_name }}
        run: |
          node copyAndProtectSheet.js
