name: Deploy and Run Google Apps Script

on:
  workflow_dispatch:
    inputs:
      google_spreadsheet_id:
        description: 'Google Spreadsheet ID'
        default: '1Kwe4PFodciXo-XDX2bHN8F-CRAmopguoI9YKFX6piaQ'
        required: false
      google_sheet_id:
        description: 'Google Sheet ID'
        default: 118145754
        required: false
      new_sheet_name:
        description: 'New Sheet name'
        default: 'v0.0.1'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Authenticate clasp
        env:
          CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}
        run: |
          echo "$CLASP_CREDENTIALS" > ~/.clasprc.json

      - name: Create .claspignore
        run: |
          echo "node_modules/" > .claspignore
          echo "*.log" >> .claspignore
          echo "*.json" >> .claspignore
          echo "!appsscript.json" >> .claspignore
          echo "*.csv" >> .claspignore

      - name: Push and Deploy Script to Google Apps Script
        run: clasp push

      - name: Run Google Apps Script Function
        env:
          GOOGLE_SHEET_ID: ${{ github.event.inputs.google_spreadsheet_id }}
          SHEET_ID: ${{ github.event.inputs.google_sheet_id }}
          NEW_SHEET_NAME: ${{ github.event.inputs.new_sheet_name }}
        run: |
          clasp run copyAndProtectSheet --params "[\"$GOOGLE_SHEET_ID\", $SHEET_ID, \"$NEW_SHEET_NAME\"]"
